#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list

install:
  export PIPENV_VENV_IN_PROJECT=1
  pipenv install --dev

# show dotenv-load
build:
  pipenv run package  

publish:
  pipenv run twine upload --repository codeartifact ./dist/codeartifact_test_package-0.0.2.tar.gz

