# syntax=docker/dockerfile:1.10.0
FROM python:3.11.3-slim-buster AS build-env

RUN pip install pipenv

WORKDIR /workbench
COPY ./Pipfile /workbench/Pipfile

# TODO: If no lock file is present, create one
# Need to make these two lines dynamic. 
#COPY ./Pipfile.lock /workbench/Pipfile.lock 
RUN pipenv lock 

RUN pipenv requirements > ./requirements.txt
RUN python -m venv /workbench/venv
ENV PATH="/workbench/venv/bin:$PATH"
RUN pip install --no-cache-dir -r ./requirements.txt 

# **************************
# * Final stage
# **************************
FROM python:3.11.3-slim-buster AS final

RUN apt-get update \
    && apt-get install -fy -qq --no-install-recommends ca-certificates \
    && apt-get clean 

WORKDIR /workbench

ARG USERID=1000
ARG GROUPID=1000
RUN addgroup --system --gid $GROUPID appuser
RUN adduser --system --uid $USERID --gid $GROUPID appuser

COPY --chmod=755 <<EOF /workbench/.env
export TEST_CONFIG="This is a test value from .env"
export PATH="/workbench/venv/bin:$PATH"
export LANG=C.UTF-8
export PYTHONDONTWRITEBYTECODE=1
export PYTHONUNBUFFERED=1
EOF

COPY --from=build-env /workbench/venv /workbench/venv
COPY ./tests /workbench/tests
COPY ./data /workbench/data
COPY ./main.py ./logging_config.yaml /workbench/

COPY --chmod=755 <<EOF /workbench/start.sh
#!/usr/bin/env bash
. ./.env
env
pip list
python main.py --test
EOF

USER appuser
CMD ["./start.sh"]

