set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list

clean:
  rm -rf ./.venv
  rm Pipfile.lock

install:
  export PIPENV_IGNORE_VIRTUALENVS=1
  export PIPENV_VENV_IN_PROJECT=1
  pipenv install --dev --python=$(pyenv which python) --verbose

start_local:
  pipenv run start:test

build_image distro:
  docker buildx build --progress=plain --load -f Dockerfile.{{ distro }} -t 43_chainguard_{{ distro }}:latest .

start distro: (build_image distro)
  docker run 43_chainguard_{{ distro }}:latest

dive distro: (build_image distro)
  dive 43_chainguard_{{ distro }}:latest

details distro: (build_image distro)
  @echo "******************************"
  @echo "** Labels"
  @echo "******************************"
  docker inspect -f '{{{{.Config.Labels}}}}' 43_chainguard_{{ distro }}:latest
  @echo "******************************"
  @echo "** Dive CI"
  @echo "******************************"
  dive 43_chainguard_{{ distro }}:latest --ci || true
  @echo "******************************"
  @echo "** Size"
  @echo "******************************"
  container-diff analyze --json daemon://43_chainguard_{{ distro }}:latest | jq .
