swagger: "2.0"
info:
  title: "Example swagger service"
  description: "An example of a swagger service"
  version: "1.0.0"

consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  # /:
  #   get:
  #     tags: [home]
  #     operationId: app.home.home
  #     summary: Home page
  #     responses:
  #       '200':
  #         description: Home page

  # /favicon.ico:
  #   get:
  #     tags: [favicon]
  #     operationId: app.home.favicon
  #     summary: favicon
  #     responses:
  #       '200':
  #         description: Favicon.ico

  # /metrics:
  #   get:
  #     tags: [metrics]
  #     summary: Metrics
  #     responses:
  #       '200':
  #         description: Metrics

  /health:
    get:
      operationId: app.health.health
      summary: Health Check
      responses:
        '200':
          description: Status message for current health

  /ready:
    get:
      operationId: app.ready.ready
      summary: Readiness Check
      responses:
        '200':
          description: Status message for current readiness

