services:
    collector:
      image: otel/opentelemetry-collector-contrib:0.107.0
      command: ["--config=/etc/otel-collector-config.yaml", "--config=/etc/otel-collector-config-extras.yaml", "--feature-gates=-component.UseLocalHostAsDefaultHost"]
      environment:
        - HONEYCOMB_APIKEY=${HONEYCOMB_APIKEY}
        - HONEYCOMB_SERVICENAME=${HONEYCOMB_SERVICENAME}
        - HONEYCOMB_METRICS_DATASET=${HONEYCOMB_METRICS_DATASET}
        - CORALOGIX_DOMAIN=${CORALOGIX_DOMAIN}
        - CORALOGIX_APP_NAME=${CORALOGIX_APP_NAME}
        - CORALOGIX_SUBSYS_NAME=${CORALOGIX_SUBSYS_NAME}
        - CORALOGIX_PRIVATE_KEY=${CORALOGIX_PRIVATE_KEY}       
      volumes:
        - ./collector/${COLLECTOR_CONFIG_TYPE}/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        - ./collector/${COLLECTOR_CONFIG_TYPE}/otel-collector-config-extras.yaml:/etc/otel-collector-config-extras.yaml
      ports:
        - "1888:1888"   # pprof extension
        - "8888:8888"   # Prometheus metrics exposed by the collector
        - "8889:8889"   # Prometheus exporter metrics
        - "9464:9464"          # Prometheus exporter
        - "13133:13133" # health_check extension
        - "4317:4317"        # OTLP gRPC receiver
        - "4318:4318"        # OTLP http receiver
        - "55670:55679" # zpages extension
      networks:
        - service_bridge  

networks:
  service_bridge:
    driver: bridge
