set dotenv-load := true

#export PYVERSION := "cp311-cp311"
export PYVERSION := "pp310-pypy310_pp73"
export IMAGE_NAME := "38_build_custom_package:latest"

# default lists actions
default:
  @just -f justfile --list

clean:
  rm -rf ./out
  mkdir -p ./out

build_image:
  docker build --progress=plain --build-arg PYVERSION=${PYVERSION} -f Dockerfile.manylinux -t ${IMAGE_NAME} .

build: build_image
  docker run -it --rm -e PYVERSION=${PYVERSION} -v ./out:/out ${IMAGE_NAME} 

debug: build_image
  docker run -it --rm -e PYVERSION=${PYVERSION} -v ./out:/out --entrypoint /bin/bash ${IMAGE_NAME} 

